version: "2"

services:
    mariadb:
        image: docker.io/bitnami/mariadb:10.6
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            # MYSQL_USER: "${DB_USERNAME}"
            # MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            TZ: "UTC"
    myapp:
        image: docker.io/bitnami/laravel:10
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_USERNAME=bn_myapp
            - DB_DATABASE=bitnami_myapp
        volumes:
            - "./laravel-docker-full/src:/app"
        depends_on:
            - mariadb
